// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp3m18ewTVUdnuYYxJZMAlLXdoMx7U5qg',
    appId: '1:514596206715:web:677077fb90f07240afcade',
    messagingSenderId: '514596206715',
    projectId: 'myclass-12',
    authDomain: 'myclass-12.firebaseapp.com',
    storageBucket: 'myclass-12.firebasestorage.app',
    measurementId: 'G-7SL3D5J6HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAut-RA4j8J7Mnhv0CT2Rs3Nenij0x3Syo',
    appId: '1:514596206715:android:8c1de2af39f76037afcade',
    messagingSenderId: '514596206715',
    projectId: 'myclass-12',
    storageBucket: 'myclass-12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS7k2OLfbksjCL3dXsAiJAG7OYaeE4bZU',
    appId: '1:514596206715:ios:64f0a5f25aaead04afcade',
    messagingSenderId: '514596206715',
    projectId: 'myclass-12',
    storageBucket: 'myclass-12.firebasestorage.app',
    iosBundleId: 'com.example.samip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp3m18ewTVUdnuYYxJZMAlLXdoMx7U5qg',
    appId: '1:514596206715:web:2494d97fb80e5b0cafcade',
    messagingSenderId: '514596206715',
    projectId: 'myclass-12',
    authDomain: 'myclass-12.firebaseapp.com',
    storageBucket: 'myclass-12.firebasestorage.app',
    measurementId: 'G-HCZ0JLVVZK',
  );
}
